In [ ]:
import numpy as np

RANDOM MODULE IS SUB-PACKAGE OF NUMPY

In [ ]:
N=np.ones((4,8))
print(N)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
A=np.random.rand(1)
print(A)

[0.66339877]


In [ ]:
B=np.random.rand(8,4) #rand-range is between 0 and 1
print(B)

[[0.44710556 0.70343578 0.5511194  0.15674943]
 [0.67944511 0.29471383 0.47849895 0.57657813]
 [0.78875544 0.06585902 0.91450866 0.26452991]
 [0.15324077 0.7026306  0.80034349 0.7087011 ]
 [0.06175068 0.43957179 0.50126301 0.29192061]
 [0.62963304 0.68837365 0.36208082 0.20950554]
 [0.60327736 0.68220652 0.70823164 0.24456726]
 [0.42955578 0.08283059 0.33935455 0.46682448]]


In [ ]:
C=10*np.random.rand(8,4) #rand-range is between 0 and 1
print(C)

[[3.01835207 8.43068869 4.80150947 2.35169576]
 [8.212324   6.15170744 4.48617583 9.95514014]
 [6.20950209 8.23854843 1.78981181 0.92785992]
 [1.42876376 8.184541   6.07080343 1.07493655]
 [5.53739826 4.81544677 3.1868685  0.96646077]
 [8.92926693 8.24071158 9.90245319 0.30195684]
 [1.81462771 7.26794653 3.20380869 6.7754956 ]
 [9.63438118 7.77654144 1.96598381 0.5755205 ]]


In [ ]:
D=np.floor(10*np.random.rand(8,4)) #rand-range is between 0 and 1
print(D)

[[7. 9. 6. 9.]
 [5. 2. 7. 6.]
 [1. 0. 4. 2.]
 [2. 6. 9. 6.]
 [7. 6. 8. 1.]
 [6. 3. 7. 6.]
 [4. 0. 5. 7.]
 [2. 3. 5. 7.]]


In [ ]:
E=np.arange(1,33).reshape(8,4)
print(E)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(E,4) #Vertical split

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.split(E,(3,5)) #split it after 3rd row and 5th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
F=np.arange(1,33).reshape(4,8)
print(F)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(F,4) #Horizontal split

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(F,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [ ]:
np.hsplit(F,(2,5))

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5],
        [11, 12, 13],
        [19, 20, 21],
        [27, 28, 29]]),
 array([[ 6,  7,  8],
        [14, 15, 16],
        [22, 23, 24],
        [30, 31, 32]])]

TRIGONOMETRY

In [ ]:
np.pi

3.141592653589793

In [ ]:
G=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(G)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(G)   #convert radians to degrees

array([ 45.,  60.,  90., 180.])

In [ ]:
np.deg2rad(G)     #convert degrees to radians

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
np.sin(1)

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
p=np.tan(1)
print(p)

1.5574077246549023


STATISTICS

In [ ]:
st=np.array([23,45,67,89,10,85])
print(st)

[23 45 67 89 10 85]


In [ ]:
np.mean(st)

53.166666666666664

In [ ]:
np.median(st)

56.0

In [ ]:
np.var(st)         #variance formula

888.138888888889

In [ ]:
np.std(st)      #standard deviation formula

29.801659163356813

In [ ]:
I=np.arange(1,5).reshape(2,2)
print(I)

[[1 2]
 [3 4]]


In [ ]:
I=np.linalg.inv(I)  #inverse of a matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.argmax(I)

3

In [ ]:
J=np.floor(10*np.random.rand(24)).reshape(6,4)
print(J)

[[4. 7. 5. 8.]
 [7. 8. 6. 1.]
 [5. 0. 5. 7.]
 [0. 5. 6. 3.]
 [6. 4. 6. 7.]
 [3. 1. 7. 0.]]


In [ ]:
np.argmax(J) #maximum number index will print (9 is biggest number in above number & it print 9 index)

0

In [ ]:
np.argmax(J,1)  #biggest number in every row

array([0, 3, 1, 1, 1, 1])

In [ ]:
np.argmin(J,axis=0)

array([3, 0, 1, 5])

In [ ]:
np.argmax(J,axis=1)

array([1, 0, 3, 0, 0, 1])

In [ ]:
print(np.argmin(J))

20


In [ ]:
print(np.argmin(J,axis=1))

[0 1 1 2 2 0]


In [ ]:
print(np.argmin(J,axis=0))

[5 1 5 4]


SEARCHING

In [ ]:
K=np.array([36,48,93,58,77])
print(np.where(K%2==0))

(array([0, 1, 3]),)


In [ ]:
L=np.array([24,16,7,17,54,60])
print(np.where(L%6==0))

(array([0, 4, 5]),)


In [ ]:
M=np.array([1,2,3,4,5,6,7,8,9])
x=np.searchsorted(M,7)
print(x)

6


In [ ]:
N=np.array([7,46,6,1,4])
x=np.searchsorted(L,1)
print(x)

0


In [ ]:
print(np.sort(N))

[ 1  4  6  7 46]


In [ ]:
O=np.array(['hi','hello','good','morning','krishna','radha']) #sorted array
print(np.sort(O))

['good' 'hello' 'hi' 'krishna' 'morning' 'radha']


In [ ]:
P=np.array([[3,4,1],[8,5,2]]) #2D sorted ->sorting happens within row
print(np.sort(P))

[[1 3 4]
 [2 5 8]]


FILTERING

In [ ]:
Q=np.array([40,74,77,93,44])
filt=np.where(Q%2==0)
print(filt)

(array([0, 1, 4]),)


In [ ]:
print(Q[filt])

[40 74 44]


ITERATING TO ARRAYS

In [ ]:
names=np.array(['Jwalitha','Lalli','Likhi','Suji','Prassu','Sudha'])
initials=np.array(['K','Y','S','E','CH','M'])
for i,j in zip(initials,names):
  print(i,".",j)

K . Jwalitha
Y . Lalli
S . Likhi
E . Suji
CH . Prassu
M . Sudha


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([70,80,90,21,23,17])
n=np.multiply(a1,a2)
print(n)


[ 700 1600 2700  840 1150 1020]


In [ ]:
n=np.divide(a1,a2)
print(n)

[0.14285714 0.25       0.33333333 1.9047619  2.17391304 3.52941176]


In [ ]:
n=np.add(a1,a2)
print(n)

[ 80 100 120  61  73  77]


In [ ]:
n=np.mod(a1,a2)
print(n)

[10 20 30 19  4  9]


In [ ]:
n=np.divmod(a1,a2)
print(n)

(array([0, 0, 0, 1, 2, 3]), array([10, 20, 30, 19,  4,  9]))


LOGARITHMS

In [ ]:
b1=7
print(np.log(b1)) #natural log e

1.9459101490553132


In [ ]:
b1=7
print(np.log2(b1)) #log base 2

2.807354922057604


In [ ]:
b1=7
print(np.log10(b1)) #log base 10

0.8450980400142568


In [ ]:
S=np.array([1,2,3,4,5])
print(np.log(S))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


Other Mathematical Functions

In [ ]:
a3=np.array([6,7,8,9])
y=np.cumprod(a3)
print(y)

[   6   42  336 3024]


In [ ]:
y=np.cumsum(a3)
print(y)

[ 47 103 127 217]


In [ ]:
a3=np.array([47,56,24,90]) #e2-e1
z=np.diff(a3)
print(z)

[  9 -32  66]


In [ ]:
n1=567
n2=654
s=np.lcm(n1,n2)
print(s)

123606


In [ ]:
s=np.gcd(n1,n2)
print(s)

3


In [ ]:
t=np.array([7,23,25,17])
gc=np.gcd.reduce(t)       #takes multiple inputs gives single output
print(gc)

1


In [ ]:
t=np.array([7,23,25,17])
lc=np.lcm.reduce(t)       #takes multiple inputs gives single output
print(lc)

68425
